services:
  - type: web
    name: better-golf-league-tracker
    runtime: python
    rootDir: app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: false
      - key: SESSION_COOKIE_SECURE
        value: true
